In [ ]:
import numpy as np
import cv2

img = cv2.imread("opencv-logo.png")
print(img.shape)
#img = cv2.resize(img,(512,512))
imgray = cv2.cvtColor(img , cv2.COLOR_BGR2GRAY)

cv2.imshow("IMAGE",img)
cv2.imshow("Image Gray",imgray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [24]:
import numpy as np
import cv2

img = cv2.imread("opencv-logo-white.png")
print(img.shape)
img = cv2.resize(img,(694,500))
imgray = cv2.cvtColor(img , cv2.COLOR_BGR2GRAY)

ret, thresh = cv2.threshold(imgray, 127, 255, 0)
contours, hierarchy = cv2.findContours(thresh,cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)
print("Number of contours = " + str(len(contours)))
print(contours[0])

cv2.drawContours(img, contours, -1, (0, 255, 0), 3)

cv2.imshow("IMAGE",img)
cv2.imshow("Image Gray",imgray)

cv2.waitKey(0)
cv2.destroyAllWindows()

(238, 180, 3)
Number of contours = 12
[[[352 418]]

 [[351 419]]

 [[351 420]]

 [[351 421]]

 [[351 422]]

 [[351 423]]

 [[351 424]]

 [[351 425]]

 [[351 426]]

 [[351 427]]

 [[351 428]]

 [[351 429]]

 [[351 430]]

 [[351 431]]

 [[351 432]]

 [[351 433]]

 [[351 434]]

 [[351 435]]

 [[351 436]]

 [[351 437]]

 [[351 438]]

 [[351 439]]

 [[351 440]]

 [[351 441]]

 [[351 442]]

 [[351 443]]

 [[351 444]]

 [[351 445]]

 [[351 446]]

 [[351 447]]

 [[351 448]]

 [[351 449]]

 [[351 450]]

 [[351 451]]

 [[351 452]]

 [[351 453]]

 [[351 454]]

 [[351 455]]

 [[351 456]]

 [[351 457]]

 [[351 458]]

 [[351 459]]

 [[351 460]]

 [[351 461]]

 [[351 462]]

 [[351 463]]

 [[351 464]]

 [[351 465]]

 [[351 466]]

 [[351 467]]

 [[351 468]]

 [[351 469]]

 [[351 470]]

 [[351 471]]

 [[351 472]]

 [[351 473]]

 [[351 474]]

 [[351 475]]

 [[351 476]]

 [[351 477]]

 [[351 478]]

 [[351 479]]

 [[351 480]]

 [[352 480]]

 [[353 480]]

 [[354 480]]

 [[355 480]]

 [[356 480]]

 [[357 480

In [18]:
import numpy as np
import cv2

img = cv2.imread("chessboard.png")
print(img.shape)
img = cv2.resize(img,(512,512))
imgray = cv2.cvtColor(img , cv2.COLOR_BGR2GRAY)

ret, thresh = cv2.threshold(imgray, 127, 255, 0)
contours, hierarchy = cv2.findContours(thresh,cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)
print("Number of contours = " + str(len(contours)))
print(contours[0])

cv2.drawContours(img, contours, -1, (0, 255, 0), 3)

cv2.imshow("IMAGE",img)
cv2.imshow("Image Gray",imgray)

cv2.waitKey(0)
cv2.destroyAllWindows()

(3723, 3595, 3)
Number of contours = 19
[[[0 0]]

 [[0 1]]

 [[0 2]]

 ...

 [[3 0]]

 [[2 0]]

 [[1 0]]]
