In [2]:
import cv2
import numpy as np

img = cv2.imread("messi5.jpg")

cv2.imshow("image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
import cv2
import numpy as np

img = cv2.imread("messi5.jpg")
grey_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
template = cv2.imread("messi5-face.jpg", 0)

res = cv2.matchTemplate(grey_img, template, cv2.TM_CCOEFF_NORMED)
print(res)

cv2.imshow("image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[ 0.11534169  0.1096395   0.1016371  ...  0.02700457  0.00867547
  -0.00816518]
 [ 0.10197284  0.09765939  0.09106244 ...  0.01293948 -0.00559146
  -0.02232698]
 [ 0.08704131  0.08369385  0.07809284 ...  0.00034459 -0.01799751
  -0.03434851]
 ...
 [ 0.24374187  0.24369498  0.24921656 ... -0.02559779 -0.02310547
  -0.03058246]
 [ 0.25909117  0.25757876  0.26058397 ... -0.05020759 -0.04560031
  -0.04685766]
 [ 0.25098836  0.24975081  0.2527764  ... -0.06452509 -0.06000135
  -0.0597908 ]]


In [8]:
import cv2
import numpy as np

img = cv2.imread("messi5.jpg")
grey_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
template = cv2.imread("messi5-face.jpg", 0)

res = cv2.matchTemplate(grey_img, template, cv2.TM_CCOEFF_NORMED)
print(res)
threshold = 0.8;
loc = np.where(res >= threshold)
print(loc)


cv2.imshow("image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[ 0.11534169  0.1096395   0.1016371  ...  0.02700457  0.00867547
  -0.00816518]
 [ 0.10197284  0.09765939  0.09106244 ...  0.01293948 -0.00559146
  -0.02232698]
 [ 0.08704131  0.08369385  0.07809284 ...  0.00034459 -0.01799751
  -0.03434851]
 ...
 [ 0.24374187  0.24369498  0.24921656 ... -0.02559779 -0.02310547
  -0.03058246]
 [ 0.25909117  0.25757876  0.26058397 ... -0.05020759 -0.04560031
  -0.04685766]
 [ 0.25098836  0.24975081  0.2527764  ... -0.06452509 -0.06000135
  -0.0597908 ]]
(array([64, 64, 64, 65, 65, 65, 65, 66, 66, 66], dtype=int64), array([207, 208, 209, 207, 208, 209, 210, 207, 208, 209], dtype=int64))


In [10]:
import cv2
import numpy as np

img = cv2.imread("messi5.jpg")
grey_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
template = cv2.imread("messi5-face.jpg", 0)

res = cv2.matchTemplate(grey_img, template, cv2.TM_CCOEFF_NORMED)
print(res)
threshold = 0.95;
loc = np.where(res >= threshold)
print(loc)


cv2.imshow("image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[ 0.11534169  0.1096395   0.1016371  ...  0.02700457  0.00867547
  -0.00816518]
 [ 0.10197284  0.09765939  0.09106244 ...  0.01293948 -0.00559146
  -0.02232698]
 [ 0.08704131  0.08369385  0.07809284 ...  0.00034459 -0.01799751
  -0.03434851]
 ...
 [ 0.24374187  0.24369498  0.24921656 ... -0.02559779 -0.02310547
  -0.03058246]
 [ 0.25909117  0.25757876  0.26058397 ... -0.05020759 -0.04560031
  -0.04685766]
 [ 0.25098836  0.24975081  0.2527764  ... -0.06452509 -0.06000135
  -0.0597908 ]]
(array([65], dtype=int64), array([208], dtype=int64))


In [11]:
import cv2
import numpy as np

img = cv2.imread("messi5.jpg")
grey_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
template = cv2.imread("messi5-face.jpg", 0)
w, h = template.shape[::-1]

res = cv2.matchTemplate(grey_img, template, cv2.TM_CCOEFF_NORMED)
print(res)
threshold = 0.95;
loc = np.where(res >= threshold)
print(loc)
for pt in zip(*loc[::-1]):
    cv2.rectangle(img, pt, (pt[0] + w, pt[1] + h), (0,0,255), 2)

cv2.imshow("image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[ 0.11534169  0.1096395   0.1016371  ...  0.02700457  0.00867547
  -0.00816518]
 [ 0.10197284  0.09765939  0.09106244 ...  0.01293948 -0.00559146
  -0.02232698]
 [ 0.08704131  0.08369385  0.07809284 ...  0.00034459 -0.01799751
  -0.03434851]
 ...
 [ 0.24374187  0.24369498  0.24921656 ... -0.02559779 -0.02310547
  -0.03058246]
 [ 0.25909117  0.25757876  0.26058397 ... -0.05020759 -0.04560031
  -0.04685766]
 [ 0.25098836  0.24975081  0.2527764  ... -0.06452509 -0.06000135
  -0.0597908 ]]
(array([65], dtype=int64), array([208], dtype=int64))


In [16]:
import cv2
import numpy as np

img = cv2.imread("temp.jpg")
grey_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
template = cv2.imread("temp-face.jpg", 0)
w, h = template.shape[::-1]

res = cv2.matchTemplate(grey_img, template, cv2.TM_CCOEFF_NORMED)
print(res)
threshold = 0.7;
loc = np.where(res >= threshold)
print(loc)
for pt in zip(*loc[::-1]):
    cv2.rectangle(img, pt, (pt[0] + w, pt[1] + h), (0,0,255), 2)

cv2.imshow("image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(array([70, 70, 70, 70, 70, 71, 71, 71, 71, 71, 71, 71, 71, 72, 72, 72, 72,
       72, 72, 72, 72, 72, 72, 72, 72, 73, 73, 73, 73, 73, 73, 73, 73, 73,
       73, 73, 73, 73, 73, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 75, 75,
       75, 75, 75, 76, 76], dtype=int64), array([267, 268, 511, 512, 513, 266, 267, 268, 511, 512, 513, 640, 641,
       265, 266, 267, 268, 389, 511, 512, 513, 639, 640, 641, 642, 140,
       141, 266, 267, 268, 388, 389, 511, 512, 513, 639, 640, 641, 642,
       139, 140, 141, 142, 266, 267, 512, 639, 640, 641, 139, 140, 141,
       142, 640, 140, 141], dtype=int64))
